### ISSUE TITLE
Crash on merging multiple duplicate mentions

### ISSUE THREAD

**Issue by andreasvc** [ns-moosavi/coval#2]
The attached test case results in the following traceback:
```
$ python3 scorer.py dups.key.txt dups.response.txt
A single mention cannot be assigned to more than one cluster
The following clusters will be merged: [0, 1, 2]
A single mention cannot be assigned to more than one cluster
The following clusters will be merged: [1, 2]
Merging [0, 1, 2] clusters
Merging [1, 2] clusters
Traceback (most recent call last):
  File "scorer.py", line 65, in <module>
    main()
  File "scorer.py", line 42, in main
    evaluate(key_file, sys_file, metrics, NP_only, remove_nested, keep_singletons)
  File "scorer.py", line 46, in evaluate
    doc_coref_infos = reader.get_coref_infos(key_file, sys_file, NP_only, remove_nested, keep_singletons)
  File "[...]/coval/conll/reader.py", line 387, in get_coref_infos
    sys_clusters, singletons_num  = get_doc_mentions(doc, sys_doc_lines[doc], keep_singletons)
  File "[...]/coval/conll/reader.py", line 70, in get_doc_mentions
    merged.extend(clusters[c])
KeyError: 1
```

What I suppose is happening is that after the first occurrence of the duplicate mentions, they have been merged, and cannot be merged again on the second occurrence.

[dups.response.txt](https://github.com/ns-moosavi/coval/files/3251970/dups.response.txt)
[dups.key.txt](https://github.com/ns-moosavi/coval/files/3251971/dups.key.txt)

**Comment by ns-moosavi** [comment]
Thanks for reporting the issue.
I am going to update the scorer with a new option and I will also fix this.
